apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 454830823500.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 454830823500.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 31f54a3b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
